In [1]:
import os

In [2]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam, SGD 

ModuleNotFoundError: No module named 'tensorflow'

In [3]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv('last_clean.csv',encoding="cp949")

In [5]:
df[['사고']]

사고
0       1
1       1
2       1
3       0
4       1
...    ..
28935   0
28936   0
28937   1
28938   1
28939   0

[28940 rows x 1 columns]

In [6]:
y_data = df[['사고']]
y_data = y_data.astype(np.float32)
len(y_data)

28940

In [24]:
df.rename(columns={'유의파고':'유의파고(m)', '파향':'파향(deg)','최대파주기':'최대파주기(sec)','풍속':'풍속(m/s)', '풍향':'풍향(deg)'})

date  해구번호  유의파고(m)  파향(deg)  최대파주기(sec)  풍속(m/s)  \
0      2018-04-29 06:00:00   105      0.3    204.0         4.1      5.4   
1      2017-05-13 06:00:00   153      0.5    225.0         5.2      5.2   
2      2019-06-29 18:00:00    62      0.7     50.0         6.6      0.7   
3      2019-07-27 15:00:00  8126      1.1    203.0         6.4      5.0   
4      2020-04-17 06:00:00   619      1.0    185.0         4.5      9.2   
...                    ...   ...      ...      ...         ...      ...   
28935  2018-12-21 15:00:00   840      1.9    114.0        12.3      7.1   
28936  2018-04-26 18:00:00   855      1.7     83.0        10.8      1.0   
28937  2018-06-24 12:00:00   210      0.7    188.0         6.7      3.1   
28938  2016-05-08 12:00:00    92      0.4    155.0         6.0      4.6   
28939  2020-05-21 09:00:00   595      1.4     65.0        10.3      3.4   

       풍향(deg)  사고  
0        232.0   1  
1        177.0   1  
2         18.0   1  
3        239.0   0  
4        173.0   1  
...        ...  ..  
28935    138.0   0  
28936      9.0   0  
28937    235.0   1  
28938     60.0   1  
28939    296.0   0  

[28940 rows x 8 columns]

In [10]:
x_data = df.loc[:, ['유의파고(m)','파향(deg)','최대파주기(sec)','풍속(m/s)','풍향(deg)']]
x_data = x_data.astype(np.float32)
len(x_data)

28940

In [7]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

In [11]:
scaler = StandardScaler()
x_data_scaled = scaler.fit_transform(x_data) #변수들의 스케일 달라 맞춰주는 부분

In [12]:
encoder = OneHotEncoder()
y_data_encoded = encoder.fit_transform(y_data).toarray() #정답부분을 0,1로 하기위해 원핫인코딩사용

In [13]:
x_train, x_val, y_train, y_val = train_test_split(x_data_scaled, y_data_encoded, test_size=0.2, random_state=2021)
# 전체 사고+무사고 데이터를 8:2의 비율로 train과 validation 데이터셋으로 나눔


In [22]:
x_train.shape

(23152, 5)

In [23]:
y_train

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [24]:
y_train=y_train.astype(int)
y_train

array([[0, 1],
       [0, 1],
       [0, 1],
       ...,
       [0, 1],
       [0, 1],
       [1, 0]])

In [25]:
type(x_train[0][0])
type(y_train[0][0])

numpy.int64

In [26]:
import numpy
y_train=y_train.astype(numpy.float32)
type(y_train[0][0])

numpy.float32

In [15]:
from tensorflow.keras import optimizers
import tensorflow as tf
model = Sequential() #레이어를 선형으로 연결 구성

model.add(Dense(2,input_shape=(5,) , activation='sigmoid'))

#회귀분석이라 은닉층이 sigmoid 활성화함수를 통과하는 부분 밖에 없음

model.compile(loss='binary_crossentropy', optimizer='Adam', metrics=['acc'])
#이진분류를 할때 binary_crossentropy 사용, 
#데이터양이나 은닉층이 많아질수록 시간이 오래걸리니까 이를 고안해 경사하강법 사용
#sgd를 보완한 momentum과 adagrad의 단점을 보완한 RMSProp를 합친 Adam을 옵티마이저로 설정




In [16]:
from keras.callbacks import EarlyStopping, ModelCheckpoint

early_stop=EarlyStopping(monitor='val_loss',patience=1,verbose=1)
best = ModelCheckpoint('best_model',monitor='val_acc',mode='max',verbose=1)

#최적 모델을 best에 저장
#오버피팅을 막게 early_stop을함

model.fit(
    x_train,
    y_train,
    epochs=20,
    batch_size = 3,
    verbose=1,
    validation_data=(x_val, y_val), 
    callbacks=[early_stop,best]
)

2021-08-27 07:18:40.726039: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/20
7718/7718 [==============================] - 9s 1ms/step - loss: 0.6163 - acc: 0.6890 - val_loss: 0.6078 - val_acc: 0.6913

Epoch 00001: saving model to best_model


2021-08-27 07:18:49.490743: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.


INFO:tensorflow:Assets written to: best_model/assets
Epoch 2/20
7718/7718 [==============================] - 8s 1ms/step - loss: 0.5925 - acc: 0.7092 - val_loss: 0.6019 - val_acc: 0.6980

Epoch 00002: saving model to best_model
INFO:tensorflow:Assets written to: best_model/assets
Epoch 3/20
7718/7718 [==============================] - 8s 1ms/step - loss: 0.5892 - acc: 0.7121 - val_loss: 0.6007 - val_acc: 0.7004

Epoch 00003: saving model to best_model
INFO:tensorflow:Assets written to: best_model/assets
Epoch 4/20
7718/7718 [==============================] - 8s 1ms/step - loss: 0.5888 - acc: 0.7109 - val_loss: 0.6014 - val_acc: 0.7018

Epoch 00004: saving model to best_model
INFO:tensorflow:Assets written to: best_model/assets
Epoch 00004: early stopping


In [17]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 2)                 12        
Total params: 12
Trainable params: 12
Non-trainable params: 0
_________________________________________________________________


In [18]:
from tensorflow.keras.models import load_model
loaded_model = load_model('best_model')
print('\n테스트 정확도 : %.4f'%(loaded_model.evaluate(x_val,y_val)[1]))


181/181 [==============================] - 0s 762us/step - loss: 0.6014 - acc: 0.7018

테스트 정확도 : 0.7018


In [19]:

result=loaded_model.predict(x_val, verbose=1)
print(result)

181/181 [==============================] - 0s 614us/step
[[0.38496542 0.61552066]
 [0.6678904  0.33420283]
 [0.3491872  0.652997  ]
 ...
 [0.34047604 0.6573073 ]
 [0.4376467  0.55998385]
 [0.17536947 0.8274635 ]]


In [34]:
import json
import time

In [21]:
result = pd.DataFrame(result)

In [22]:
result_df = pd.DataFrame({
    'trench_num':list(range(0,5788)),
    'loss':result[:][0],
    'acc' : result[:][1]
    })

In [ ]:
result_json = result_df.to_json(orient= 'table')
ob = json.loads(result_json)
with open("result_json.json", "w") as outfile:
    json.dump(ob, outfile, sort_keys=True, indent =4)

In [37]:
from sqlalchemy import create_engine
import pymysql

In [38]:
db_connection_str = 'mysql+pymysql://admin:hanium123!@database-1.caua660cnte5.ap-northeast-2.rds.amazonaws.com/dongjun-test-db'
db_connection = create_engine(db_connection_str)
conn = db_connection.connect()

In [23]:
result_df

trench_num      loss       acc
0              0  0.384965  0.615521
1              1  0.667890  0.334203
2              2  0.349187  0.652997
3              3  0.646790  0.354341
4              4  0.718633  0.279067
...          ...       ...       ...
5783        5783  0.565015  0.442130
5784        5784  0.643757  0.353158
5785        5785  0.340476  0.657307
5786        5786  0.437647  0.559984
5787        5787  0.175369  0.827464

[5788 rows x 3 columns]

In [ ]:
dtypesql = {'trench_num':sqlalchemy.types.integer, 
          'loss':sqlalchemy.types.float, 
          'acc':sqlalchemy.types.float,  
}

result_df.to_sql(name='ml_result', con=db_connection, if_exists='append',index=False)